---
version: '{build}'
shallow_clone: true
platform:
  - x64
environment:
  ruby_version: "24-%Platform%"
  zlib_version: "1.2.11"
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - vs: "120"
matrix:
  fast_finish: true
branches:
  only:
    - trunk
notifications:
  - provider: Webhook
    url:
      secure: iMINHMS0nZabaDsxN9omRDsekxzVvAAzEq5ev7lN6vZ6r9zNhl3/F/7POIVyahAwVFpRDeQT/iUugpAGWmOt3eGL/lZIdqiJFZ9DjPSkP68= # #alerts
    method: POST
    # "icon_url" is the url used by `provider: Slack`
    body: >-
      {{^isPullRequest}}
        {
          "attachments": [
            {
              "title": "Build {{projectName}} {{buildVersion}} {{status}}",
              "fallback": "AppVeyor Build {{projectName}} {{buildVersion}} {{status}}",
              "title_link": "{{buildUrl}}",
              "text": "Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_",
              {{#passed}}
                "color": "#44ee44"
              {{/passed}}
              {{#failed}}
                "color": "#ee4444"
              {{/failed}}
            }
          ],
          "icon_url": "https://slack-files2.s3-us-west-2.amazonaws.com/bot_icons/2018-02-10/314363543719_48.png",
          "username": "AppVeyor CI"
        }
      {{/isPullRequest}}
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
for:
-
  matrix:
    only:
      - MSYS2_ARCH: x86_64
        MSYSTEM: MINGW64
  install:
    - ver
    - chcp
    - SET BITS=%Platform:x86=32%
    - SET BITS=%BITS:x=%
    - SET OPENSSL_DIR=c:\OpenSSL-Win%BITS%
    - SET ruby_path=C:\Ruby%ruby_version:-x86=%
    - SET PATH=\usr\local\bin;%ruby_path%\bin;%PATH%;C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin
    - ruby --version
    - mkdir \usr\local\bin
    - mkdir \usr\local\include
    - mkdir \usr\local\lib
  build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
    - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
    - bash -lc "pacman --noconfirm -S --needed base-devel"
    - bash -lc `which autoconf`
    - |
      sh -ex -c '
        ./configure --disable-install-doc --prefix=/usr/local
        mingw32-make -j$(nproc)
        mingw32-make -j$(nproc) install
      '
    - \usr\bin\ruby -v -e "p :locale => Encoding.find('locale'), :filesystem => Encoding.find('filesystem')"
  test_script:
    - echo hello
-
  matrix:
    only:
      - vs: "120"
  install:
    - ver
  build_script:
    - ver
  test_script:
    - ver
