# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get update && sudo apt-get install ruby bison
      autoconf
      ./configure
      make
    displayName: 'make'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      autoconf
      ./configure
      make
    displayName: 'make'
